spring:
  profiles: pengcheng
  datasource:
    # MySQL
    dbcp2:
      url: jdbc:mysql://localhost:3306/migration_helper?serverTimezone=UTC
      username: migration_helper
      password: mhsql
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-total: 100
  data:
    mongodb:
      uri: mongodb://localhost:27017/migration_helper

logging:
  config: classpath:log4j2.local.yaml

server:
  port: 8080

migration-helper:
  job:
    enabled: None
  thread-pool:
    thread-count: 24
    calc-thread-count: 12
  library-identity:
    maven-url-base: https://repo1.maven.org/maven2/
    download-path: jar-download
  repository-analysis:
    pom-only: true
  git-repository-analysis:
    repository-path: ../
  woc-repository-analysis: # TODO: configure for PENGCHENG
    p2cBase: /da0_data/basemaps/p2cFullQ.
    c2pcBase: /da0_data/basemaps/c2pcFullQ.
    c2bBase: /da0_data/basemaps/c2bFullQ.
    b2fBase: /da0_data/basemaps/b2fFullQ.
    c2taBase: /da0_data/basemaps/c2taFullQ.
    blobIndexBase: /fast/All.sha1o/sha1.blob_ # da4 only
    commitIndexBase: /fast/All.sha1c/commit_ # da4 only
    treeIndexBase: /fast/All.sha1c/tree_ # da4 only
    blobContentBase: /data/All.blobs/blob_ # da4 only
  woc-repo-analysis-job:
    repository-list-file: repositories.csv
  libraries-io-import:
    project-with-repository-path: export/LibrariesIOProjectWithRepositories.csv
  lio-jar-parse:
    data-source: all
    limit-count: 1000
    extract-version-only: false
    extract-dependencies: false
    reverse-order: false
    random-order: false
  dependency-change-pattern-analysis:
    method-change-support-file: export/GAChangeInMethodChange-all.csv
    dependency-seq-file: export/RepositoryDepSeq-withCommit.csv
  evaluation:
    ground-truth-file: test_data/ground-truth.csv